// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDcmDOOtnqWoQUtjKrgLNXGCT8P38xYQ',
    appId: '1:730994569511:web:88dcdcec7978d6b59a3902',
    messagingSenderId: '730994569511',
    projectId: 'glamgig-f0a17',
    authDomain: 'glamgig-f0a17.firebaseapp.com',
    storageBucket: 'glamgig-f0a17.appspot.com',
    measurementId: 'G-Y0BF86V9CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXGYpF-3xKXWL3SG43Sc4h0q43KHizE_U',
    appId: '1:730994569511:android:b86f0569f466ba8c9a3902',
    messagingSenderId: '730994569511',
    projectId: 'glamgig-f0a17',
    storageBucket: 'glamgig-f0a17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7AGEr-ZNITnA12pj_gvapkMSkcIVgJaY',
    appId: '1:730994569511:ios:7f94847eda002cb29a3902',
    messagingSenderId: '730994569511',
    projectId: 'glamgig-f0a17',
    storageBucket: 'glamgig-f0a17.appspot.com',
    iosClientId: '730994569511-beol8of5u7fejhbn0pjbo6l2assgi654.apps.googleusercontent.com',
    iosBundleId: 'com.softwareeng.glamgig.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7AGEr-ZNITnA12pj_gvapkMSkcIVgJaY',
    appId: '1:730994569511:ios:5951c58c31e5aabe9a3902',
    messagingSenderId: '730994569511',
    projectId: 'glamgig-f0a17',
    storageBucket: 'glamgig-f0a17.appspot.com',
    iosClientId: '730994569511-3pk83krnauahokjs1qovs3g633icn6g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonUser.RunnerTests',
  );
}
